### PR TITLE
GUA-597 move data structures to test helpers

### PR DESCRIPTION
**Pull request by divyaparameswaran**

### CODE REVIEW

**Comment by DougsCER** [comment]
@divyaparameswaran most file names seem to be snake-case but testHelpers is camel. Is there a reason for this?

**Comment by divyaparameswaran** [comment]
> @divyaparameswaran most file names seem to be snake-case but testHelpers is camel. Is there a reason for this?

Thats a good point I didn't really think much about it as I was trying to get it to be consistent with the delete lambda. I am happy to change it to "-" separated.

**Comment by DougsCER** [comment]
Fair. I’d say lets pick one style and stick with it everywhere. Snake-case seems more prevalent so my vote is going with that

Regards,
Dougal

___________________
Dougal Rees (he / him)
AccessUK - Migration & Borders Technology Portfolio
+447854500779


From: Divya ***@***.***>
Date: Friday, 23 December 2022 at 11:36
To: alphagov/di-account-management-backend ***@***.***>
Cc: Rees, Dougal ***@***.***>, Comment ***@***.***>
Subject: [EXT] Re: [alphagov/di-account-management-backend] GUA-597 move data structures to test helpers (PR #67)

@divyaparameswaran<https://secure-web.cisco.com/1Fo7eLaLfIWjari5Xt4lXMXgDhxwGmDnPKOSTYKrZYSL2rcuZbVS5tEabYmAHcaFWVKmDyyEKi805SAxiQiaMXL1iKc4WR52WOz1NHoEH534euLwpI21fnfGyYIivxB0FuLIhEBZ8UBLWmtsJ7oIJ0VUaQ_TkWq2jzGjNx178cNigOcW1ozlejOwIMd4bEKfss83ieQStnsBeG7yCWGbVeS01q5wyiTp8jqgXHIPOTNWdIQkEzdXbyGRLrJbx4Xxycts5Sij5XV3UbyDNB3ORGsVMyKlC0Z5WRFE6yBuZUdd68LUaUaLwYccpdYuo89-j/https%3A%2F%2Fgithub.com%2Fdivyaparameswaran> most file names seem to be snake-case but testHelpers is camel. Is there a reason for this?

Thats a good point I didn't really think much about it as I was trying to get it to be consistent with the delete lambda. I am happy to change it to "-" separated.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1UtI4-r9m9YwlVBt5MFFWSbnWnnhdrudI-McAsOdo-G97WoOOUrVK1sUfZ7dZ6i7TH8GzuPnm7G8D4aY4o92YT8VK874iJQnVIBgNpEpKatmWyeW1-7Ch1pC85YPj8dFFrno4BGKHXsA7YheFZLVbkW0H4byhdd1XVzAsiL_9mNcqtv23TF3XSro-yxZ9Pl1X_QfybrlPKkAmzYA5CCP-MSyinTrFdF1uCMHWtutoU0iMbcg6fTdKPrY1J0wABRJ_uwDN3x06suOcYw8GPTGPxIaZgM0LSUg7iU9sr5aM1QMOyCj0uf77jqYNnYR_0eiu/https%3A%2F%2Fgithub.com%2Falphagov%2Fdi-account-management-backend%2Fpull%2F67%23issuecomment-1363877166>, or unsubscribe<https://secure-web.cisco.com/1Bu4pyLjK-_wHX5fejOY8escfGibcXdSh2lB_04sv9_V4LoAGm5-yuA8kO6HiksL2vTlsTCEPyYBE616h7wU9aX2cj1Ohn8pixZ7TiZROYtMnzTndPdo26ohG_GFQdoKc5gEPoMddSZu7ymF_ceLpQW1Ks4XTYDUOkcPr57tf_7kFqoogHuHSlIximLtHFDraN5HoUudaKQ7owjyyk0cTC42aiyA_pLIjV_MxRxmeKZb2JlDYEdvDWUWDMweTpM5XO5QZi10b8Fo4hpbcej3L1lBe_7FiChFQo2VNICVLX6TLu6VuwEpCQDZv0V3yy2XL/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFYLXUZMPDSJMKUP7R6CZ5DWOWE6RANCNFSM6AAAAAATGVJTCY>.
You are receiving this because you commented.Message ID: ***@***.***>
IMPORTANT NOTICE

This communication is from Deloitte LLP, a limited liability partnership registered in England and Wales with registered number OC303675. Its registered office is 1 New Street Square, London EC4A 3HQ, United Kingdom. Deloitte LLP is the United Kingdom affiliate of Deloitte NSE LLP, a member firm of Deloitte Touche Tohmatsu Limited, a UK private company limited by guarantee (“DTTL”). DTTL and each of its member firms are legally separate and independent entities. DTTL and Deloitte NSE LLP do not provide services to clients. Please see www.deloitte.co.uk/about<https://www.deloitte.co.uk/about> to learn more about our global network of member firms. For details of our professional regulation please see Regulators<https://www2.deloitte.com/uk/en/footerlinks1/regulators-and-provision-service-regulations.html>.

This communication contains information which is confidential and may also be privileged. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), please notify ***@***.******@***.***> and destroy this message immediately. Email communications cannot be guaranteed to be secure or free from error or viruses. All emails sent to or from a @deloitte.co.uk email account are securely archived and stored by an external supplier within the European Union.

You can understand more about how we collect and use (process) your personal information in our Privacy Notice<https://www2.deloitte.com/uk/en/legal/privacy.html>.

Deloitte LLP does not accept any liability for use of or reliance on the contents of this email by any person save by the intended recipient(s) to the extent agreed in a Deloitte LLP engagement contract.

Opinions, conclusions and other information in this email which have not been delivered by way of the business of Deloitte LLP are neither given nor endorsed by it.

**Review by huwd — COMMENTED** [review]
Looks good, the conversation above makes sense, don't think i mind which syntax we follow so long as it is consistent (apologies think i introduced the first inconsistency there!)

**Comment by divyaparameswaran** [comment]
@DougsCER I have updated the test-helpers I avoided the snake case as the front-end repo also have the "-" for file names . I hope that is okay .

**Review by DougsCER — APPROVED** [review]

**Pull request merged**
